apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-conf
  namespace: identity
data:
  keycloak.conf: |-
    # --- your Keycloak config for TLS at ALB ---
    db = postgres
    db-username = db_username
    db-password = db_passsword
    db-url = jdbc:postgresql://your_database_url:5432/your_database?currentSchema=public

    # Enable features
    features = admin-fine-grained-authz,scripts,token-exchange
    health-enabled = true
    metrics-enabled = true

    # Hostname configuration (must be full URLs)
    hostname-strict = false
    hostname-strict-https = false

    # Proxy configuration (ALB terminates TLS)
    proxy = edge
    proxy-headers = xforwarded

    # HTTP listener
    http-enabled = true
    http-port = 8080

    # Admin console
    admin-enabled = true

    log-level = INFO
